// lib/articles.js
// Helper module for reading AI-generated articles
// Reads JSON files generated by GitHub Actions

import fs from 'fs';
import path from 'path';

const ARTICLES_DIR = path.join(process.cwd(), 'articles');

/**
 * Get all articles or filtered articles
 * @param {Object} options - Filter options
 * @param {string} [options.category] - Filter by category
 * @param {number} [options.limit=20] - Maximum number of articles to return
 * @param {number} [options.offset=0] - Number of articles to skip
 * @param {string} [options.tag] - Filter by tag
 * @returns {Array} Array of article objects
 */
export function getAllArticles({
  category,
  limit = 20,
  offset = 0,
  tag,
} = {}) {
  try {
    const indexPath = path.join(ARTICLES_DIR, 'index.json');
    if (!fs.existsSync(indexPath)) {
      return [];
    }

    let articles = JSON.parse(fs.readFileSync(indexPath, 'utf8'));

    // Apply filters
    if (category) {
      articles = articles.filter(
        (article) =>
          article.category?.toLowerCase() === category.toLowerCase()
      );
    }

    if (tag) {
      articles = articles.filter((article) =>
        article.tags?.some(
          (t) => t.toLowerCase() === tag.toLowerCase()
        )
      );
    }

    // Apply pagination
    return articles.slice(offset, offset + limit);
  } catch (error) {
    console.error('Error reading articles:', error);
    return [];
  }
}

/**
 * Get a single article by its slug
 * @param {string} slug - Article slug
 * @returns {Object|null} Article object or null if not found
 */
export function getArticleBySlug(slug) {
  try {
    const filePath = path.join(ARTICLES_DIR, `${slug}.json`);
    if (!fs.existsSync(filePath)) {
      return null;
    }
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    console.error(`Error reading article ${slug}:`, error);
    return null;
  }
}

/**
 * Get all article slugs for generateStaticParams
 * @returns {Array<string>} Array of article slugs
 */
export function getAllSlugs() {
  try {
    const indexPath = path.join(ARTICLES_DIR, 'index.json');
    if (!fs.existsSync(indexPath)) {
      return [];
    }
    const articles = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
    return articles.map((article) => article.slug);
  } catch (error) {
    console.error('Error reading slugs:', error);
    return [];
  }
}

/**
 * Get related articles (same category, different slug)
 * @param {string} currentSlug - Current article slug
 * @param {string} category - Category to filter by
 * @param {number} [limit=3] - Maximum number of related articles
 * @returns {Array} Array of related article objects
 */
export function getRelatedArticles(currentSlug, category, limit = 3) {
  const allArticles = getAllArticles({ category, limit: limit + 1 });
  return allArticles
    .filter((article) => article.slug !== currentSlug)
    .slice(0, limit);
}

/**
 * Get latest N articles for homepage
 * @param {number} [count=6] - Number of articles to return
 * @returns {Array} Array of latest article objects
 */
export function getLatestArticles(count = 6) {
  return getAllArticles({ limit: count });
}
